# Generated by Django 2.1.3 on 2019-10-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190807_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sponsors',
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
