# Generated by Django 2.2.10 on 2020-06-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200619_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='podcast',
            field=models.URLField(blank=True, null=True),
        ),
    ]
