# Generated by Django 2.2.13 on 2020-07-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_talk_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_members', models.PositiveIntegerField(default=0, verbose_name='amount of members')),
            ],
            options={
                'verbose_name': 'MeetUp Data',
            },
        ),
    ]
