const EVENTS_REQUEST = 'EVENTS_REQUEST'
const EVENTS_SUCCESS = 'EVENTS_SUCCESS'
const EVENTS_FAILURE = 'EVENTS_FAILURE'
const MORE_EVENTS_SUCCESS = 'MORE_EVENTS_SUCCESS'

export { EVENTS_REQUEST, EVENTS_SUCCESS, EVENTS_FAILURE, MORE_EVENTS_SUCCESS }
